version: '3.8'

services:
  backoffice:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8181
    depends_on:
      - db
    volumes:
      - ./app
    networks:
      - gf_service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "gfBackOfficeDev"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
networks:
    gf_service:
      driver: bridge
volumes:
  pg-data:
